### ISSUE TITLE
On Style

### ISSUE THREAD

**Issue by cdornan** [cdornan/cd-blog#24]
Robots or no bots?

**Comment by fiadliel** [comment]
Nice article, and I generally agree with you.

There are two (as yet unreleased) changes related to two of your points:

 - I am not sure that removing the empty lines has helped and would be tempted to leave that one with the coders.

https://github.com/tweag/ormolu/commit/145f7296f54e39a3a55ee5206602d73a9102cc2b preserves **some** whitespace within do blocks, which I think relates to most of your issue with whitespace removal.

 - This particular example — the main function of a Hakyll blog — is one that is just so singular and critical to the (blog) enterprise that I would like the option of requesting that it should not be algorithmically formatted (at least until the formatters get really good) by dropping a pragma that tells the formatter to leave well alone.

https://github.com/tweag/ormolu/commit/dde756029115fdd98f326d698a433904598c63c5 allows blocks and files to be excepted from processing.

**Comment by cdornan** [comment]
@fiadliel Excellent -- this is really good to see, but please bear in mind that I was addressing the wider issue of what kind of variance we should allow in prjects &mdash; that to me is the hard problem. Adjusting (excellent) tools the easy part. 😉

**Comment by fiadliel** [comment]
👍 I agree completely, even when the tool isn't perfect :)
